on:
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  add-manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        id: fetch
      - name: Update README
        run: |
          sed -i "/${{ github.actor }}/! s|<!-- manual -->|<!-- manual --> ![${{ github.actor }}](https://avatars.githubusercontent.com/u/${{ github.actor_id }}\{width=24 height=24\})\ ${{ github.actor }}|g" README.md
      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "${{ github.actor }} is a vandal!"
          file_pattern: README.md
